package com.softwarearchetypes.party.events;

public sealed interface RegisteredIdentifierAdditionSucceeded extends PartyRelatedEvent permits RegisteredIdentifierAdded, RegisteredIdentifierAdditionSkipped {
}
