package com.softwarearchetypes.events;

public sealed interface RegisteredIdentifierAdditionSucceeded extends PartyRelatedEvent permits RegisteredIdentifierAdded, RegisteredIdentifierAdditionSkipped {
}
