@startuml
skinparam MinClassWidth 100
skinparam linetype ortho

object Party
object Person
object Organization

object Company
object JointStock
object LimitedLiability
object LimitedPartnership

object OrganizationUnit
object Division
object Department
object Team

object PartyRole

Person -up-|> Party
Organization -up-|> Party
Company -up-|> Organization
JointStock --up-|> Company
LimitedLiability --up-|> Company
LimitedPartnership --up-|> Company
OrganizationUnit -up-|> Organization
Division --up-|> OrganizationUnit
Department --up-|> OrganizationUnit
Team --up-|> OrganizationUnit

Party "1" -- "0..*" PartyRole

@enduml